### ISSUE TITLE
battery icon issue

### ISSUE THREAD

**Issue by Stunkymonkey** [i3/i3status#203] opened 2017-02-07 21:51 UTC
i experience a weird issue with my battery icon (UNK):
![screenshot from 2017-02-07 22-44-34](https://cloud.githubusercontent.com/assets/1315818/22712990/025e94ee-ed87-11e6-82cb-146dd9fa4ac0.png)
in the previous version it showed this icon:
![screenshot from 2017-02-07 22-49-48](https://cloud.githubusercontent.com/assets/1315818/22713212/cc36bc92-ed87-11e6-9573-86911cae273b.png)
system: `Arch Linux`
version: `i3status 2.11 (2017-01-21) © 2008 Michael Stapelberg and contributors`
icon: `ttf-font-awesome 4.7.0-1`
here is my config:
[i3status](https://github.com/Stunkymonkey/dotfiles/blob/master/i3/i3status)

**Comment by Airblader** [comment] 2017-02-07 21:59
The new setting `status_unk` has been added in d59589bf9ea9b1c0f760077af0e849f6c369b446. All you need to do is set it to the icon you want it to display in this case.

I guess technically this is a breakage, which is unfortunate. It should've defaulted to one of the other formats first. We didn't consider this when merging the PR, but at least the fix is easy enough. :-)

**Comment by Airblader** [comment] 2017-02-08 17:57
@Stunkymonkey I'm going to close this issue because the root cause seems fairly clear and I think I prefer not implementing a fallback to status_full now. The breakage already happened and the fallback just hides information from the user (AFAIK unknown does mean »full« in the majority of cases, but technically it doesn't have to be that way and I'd prefer the user not to mistakenly believe their battery is full when really it might be broken).

If adding `status_unk` doesn't help, please report back.

**Closed by Airblader** 2017-02-08 17:57 UTC
Labels: bug
