### ISSUE TITLE
time/tztime format option buggy for / and \ literals

### ISSUE THREAD

**Issue by rmonico** [i3/i3status#137] opened 2016-07-14 04:45 UTC
I use my time format in the format: "%a %d/%b %H:%M", which should return now: "Qua 13/Jul 22:18", (Qua = Quarta-feira = Wednesday = Wed, I in Brazil) but this field is blank (just the space is there).

I isolated all the elements and identified the following pattern:

format = "%d\%b" => blank
format = "%d/%b" => blank
format = "%d/ %b" => "13/ Jul"
format = "%d /%b" => blank
format = "%D" => "07/13/2016" (my $LANG, $LC_TYPE and $LC_TIME are all pt_BR.UTF-8)
format = "07/13" First try: just the tray icons. 2nd try: "07/13"  (I just restarted i3 between tests O.o )
format = " 07/13 " => " 07/13 "
format = " 07/Jul " => Blank
format = "07/Jul" => Blank
format = "07/ Jul" => "07/ Jul"
format = "07 /Jul" => Blank
format = "07 /J" => Blank

The output in console is ok, that is, its showing the characters / and \ for all the examples.

Note: I using a python wrapper, but with it or without it the results were the same.

Thanks in advance!

**Comment by rmonico** [comment] 2016-07-14 04:55
# OK = Expected output
        # OKNB = OK, but no bar is shown (I think \ is a escape sequence)
        # Error = most times just the field is blank, sometimes the whole bar is empty, may be because I restarting i3 every attempt, I dont know

        #format = "J" # OK
        #format = "\J" # OKNB
        #format = "\\J" # Error
        #format = "/J" # Error
        #format = "//J" # Error
        #format = "%b" # OK
        #format = "\%b" # OKNB
        #format = "\\%b" # Error
        #format = "/%b" # Error
        #format = "//%b" # Error
        format = "/a" # Ok
        format = "//a" # Ok (Is J the problem?)
        format = "\a" # "0007" (fine, \ is a escape sequence)
        format = \\a" # Ok (Is J the problem?)

Am I doing something wrong? Thanks in advance!

**Comment by stapelberg** [comment] 2016-07-15 07:57
What’s the result of `i3status --version`?

Can you please provide an example i3status config and an strace log? Use `strace -s 2048 -v -tt -f -o /tmp/i3status.log i3status`.

In general, running i3status on the command line might be helpful to narrow down the problem.

**Comment by eplanet** [comment] 2016-07-15 18:03
I cannot reproduce the issue, slash display correctly, so are the configured output (ie "**%d/%b**" displays "**15/Jul**").

I however noticed that **%d\%b** displays **15Jul** instead of **15\Jul**, but it doesn't surprise me overmuch since by doubling it **%d\\%b** you eventually get **15\Jul**.

**Comment by rmonico** [comment] 2016-07-16 04:10
@stapelberg @eplanet
$ i3status --version                                                                                                                                                                         i3status 2.9 (2015-03-22) © 2008-2012 Michael Stapelberg and contributors

$ i3 --version                                                                                                                                                                               i3 version 4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors

$ i3bar --version
i3bar version 4.12 (2016-03-06, branch "4.12") © 2010 Axel Wagner and contributors

[strace stuff](http://pastebin.com/g8njynpM)

[i3status config file](http://pastebin.com/TRGCsFCf)

I change (automatically) the i3 theme when workspace changes using j4-make-config.
The other config files are [here](http://pastebin.com/MgpcxD6s).

In console everything is ok (/ and \ are shown). Yesterday I discovered that the problem involves i3 theme: it happens just for some of them. I checked all themes I have installed, the results are [here](http://pastebin.com/KxUPhf3t). Now I think its not a i3status issue, but failing themes issue....

**Comment by rmonico** [comment] 2016-07-16 05:21
Problem solved (and it was my fault):

After post here I look better to [themes tests file](http://pastebin.com/KxUPhf3t). And remembered that I imported (manually) some themes from [i3-style project](https://github.com/acrisci/i3-style), and, guess, which themes were wrong? Just for curiosity, [follow the diff](http://pastebin.com/r9pAhJue)

When I ran j4-make-config (with -r option) I got [{"success":true}] and the problematic two dots (:) was put in i3 config file. When I ran j4 without -r (no output) and after i3-msg reload I got again [{"success":true}].

Before you ask for [i3-msg version and strace](http://pastebin.com/gpVTKyiT):

Anyway, I take [a screenshot with the problem](https://imgur.com/1wzFFxz).

Halloween is coming, you already have a story to scare other programmers.

Thank you very much to help find the problem!

**Comment by stapelberg** [comment] 2016-07-16 07:32
Thanks for confirming, closing this issue.

**Closed by stapelberg** 2016-07-16 07:32 UTC
