### ISSUE TITLE
Volume module not working 

### ISSUE THREAD

**Issue by i716** [i3/i3status#234] opened 2017-07-10 05:05 UTC
Output of i3 --moreversion 2>&- || i3 --version:

Binary i3 version: 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08)

What I did:

Tried to add volume module:

order += "volume master"

...
volume master {
format = "♪: %volume"
format_muted = "♪: muted (%volume)"
device = "pulse:NAME-OF-THE-SINK"
}

What I saw:

no such option 'volume' if launched from terminal, otherwise status bar is not displayed.

What I expected instead:

expected to have a volume indicator

i3status version: i3status 2.11 (2017-01-21)

**Comment by eplanet** [comment] 2017-08-15 11:53
Hi @i716 and thanks for reporting the issue. However, I don't reproduce it, I have the expected output (ex: `♪: muted (0%)`).

The issue doesn't seem to be directly related to `i3status` and I wouldn't be surprised if it were `pulse`. Maybe try with `device = "default"` to see if you still reproduce?

**Comment by sinback** [comment] 2018-03-09 20:38
I have this issue too, and I've tried all of

device = "pulse:<name of my sink>", 
device = "pulse"
device = "default"

and see the same behavior described by the OP.

$ i3 --version
i3 version 4.14.1-256-gfadacdc (2018-01-15, branch "gaps-next") © 2009 Michael Stapelberg and contributors

Happened when I used the version in the Ubuntu repos:
$ i3status --version
i3status 2.10 (2016-01-01) © 2008 Michael Stapelberg and contributors

and when I upgraded to the latest release from github:
i3status --version
i3status 2.11-non-git © 2008 Michael Stapelberg and contributors

My Pulse sink is an ALSA device:
$ pacmd list-sinks | grep name:	
name: <alsa_output.pci-0000_00_1f.3.analog-stereo>

**Comment by sinback** [comment] 2018-03-09 21:12
Yikes. Nevermind. Mispelled the name of "volume master" in the configuration file. Nevermind 😅

**Comment by aminnairi** [comment] 2018-06-06 19:26
Had a similar issue, resolved by setting the `device = "pulse"` in the `~/.config/i3status/config` file while using PulseAudio as the sound server on Arch Linux x86_64.

**Comment by eplanet** [comment] 2018-11-07 21:44
Maybe we can consider closing that issue since configuring it properly seems to fix.

**Closed** 2018-11-07 21:46 UTC

**Comment by BloodyNora** [comment] 2020-09-04 23:45
I'm on FreeBSD12.1 - while i do see a volume indicator, for the love of god i can't make it display actual values. instead, for all available sinks, it will just display 100% no matter if it's muted or not. running on CLI gives no errors. it does not matter if i specify the sink by number or by name. using just `pulse` produces the same result.
