### ISSUE TITLE
Error with i3status no such option

### ISSUE THREAD

**Issue by dthielking** [i3/i3status#224] opened 2017-05-28 06:37 UTC
Output of i3status -v:

i3status 2.11 (2017-01-21) © 2008 Michael Stapelberg and contributors

Output of i3status -c i3status.conf:

internal error in cfg_init_defaults(order)
/home/thielking/.i3/i3status.conf:1: no such option 'general'

What I saw:

Error: status_command process exited unexpectedly (exit 1) in status line

What I expected instead:

Status of my configured options

Config files
https://pastebin.com/HQ08Np6N

**Comment by dthielking** [comment] 2017-05-31 14:51
Ping

**Comment by Airblader** [comment] 2017-05-31 14:54
Please don't ping. If this is very urgent for you feel free to investigate it and send a PR. I'm pretty sure this is a duplicate of #225, however.

**Comment by troglobit** [comment] 2017-05-31 15:11
Could be, although I'm confident we have unit tests in libConfuse that cover the cases listed in the referenced config sample.

**Comment by Airblader** [comment] 2017-05-31 18:31
Can you try and reproduce it with the fixed libconfuse mentioned in #225?

**Comment by Airblader** [comment] 2017-05-31 18:32
@troglobit But based on the very similar picture of the error I think it's still worth first ruling libconfuse out. :-)

**Comment by troglobit** [comment] 2017-05-31 18:42
@Airblader sure :)

**Comment by gauthma** [comment] 2017-06-02 20:57
I mistakenly reported this issue at the i3 page... see issue 2800 for a possible workaround...

https://github.com/i3/i3/issues/2800

**Comment by dthielking** [comment] 2017-06-02 21:09
I tried the same things like in issue #225. Now it works for me.

**Comment by Aventura5** [comment] 2017-06-03 21:00
@gauthma These are two different bugs. I had the same problem you did and downgrading confuse "fixed" it, but it's not really a fix because you shouldn't have to keep outdated packages. You (or I) should probably open a bug for it.

**Comment by OscarOrSomething** [comment] 2017-06-10 10:19
Still a thing with `confuse@3.2.1` (arch package).

**Comment by troglobit** [comment] 2017-06-16 19:30
Some help pin-pointing the issue you feel libConfuse is causing, and even reporting that with the libConfuse project, would be really helpful.  I may run into this myself someday if I migrate from [AwesomeWM](https://awesomewm.org/), but it's not likely to happen anytime soon ...

We have a really simple unit testing framework in libConfuse, so just a simple code snippet to reproduce the problem would be helpful to me¹.

____
¹ Current maintainer of libConfuse :smiley:

**Comment by eplanet** [comment] 2017-06-19 08:09
I ran in the same issue while upgrading from Jessie to Stretch. I had to re-compile i3status from scratch so that it would reference the right libconfuse shared object.

My guess is that people running into that issue are using a custom build of i3status and not official package. Anyhow, recompiling is fixing the issue.

**Comment by troglobit** [comment] 2017-06-19 15:19
Ah, that sounds like a very plausible explanation.  Thanks @eplanet :smiley: :+1:

**Comment by gauthma** [comment] 2017-06-24 21:09
@eplanet Indeed I had a custom (git) build of i3status, and re-building it fixed the issue.

**Comment by Airblader** [comment] 2017-06-25 14:09
As it seems to be that way → closing.

**Closed by Airblader** 2017-06-25 14:09 UTC

**Comment by jwilk** [comment] 2017-08-14 13:23
@troglobit, https://github.com/martinh/libconfuse/commit/028547932e7267781e0b203f0009d4b127b5666 changes layout of `struct cfg_t` of and `struct cfg_defvalue_t`, thereby breaking ABI.
But libConfuse didn't change SONAME. :-(
