### ISSUE TITLE
%bitrate reports wrong bitrate

### ISSUE THREAD

**Issue by legovini** [i3/i3status#44] opened 2015-07-24 19:50 UTC
At least in some common configurations (with modern Intel wifi adapters) the reported %bitrate is wrong. It is the same bitrate reported by the deprecated iwconfig, while iw reports the correct figure. Perhaps i3status should use some newer libraries.

**Comment by stapelberg** [comment] 2015-07-24 21:31
duplicate of #32

**Closed by stapelberg** 2015-07-24 21:31 UTC
