### ISSUE TITLE
Path for cpu temperature does not support wildcards

### ISSUE THREAD

**Issue by f4hy** [i3/i3status#55] opened 2015-09-04 08:19 UTC
It seems every time my machine boots up, it either puts the temperature info in

/sys/devices/platform/coretemp.0/hwmon/hwmon0/temp1_input
or
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input

With either hwmon**0** or hwmon**1** existing and the other folder doesn't exist at all. This seems to be random which one upon boot. It would be nice to be able to set the path to just include `hwmon?` or `hwmon[01]` but the path variable does not seem to support wildcards in the middle of the path.

**Comment by stapelberg** [comment] 2015-09-04 08:27
Yeah, you’d need to glob `thermal_zone` in https://github.com/i3/i3status/blob/master/src/print_cpu_temperature.c#L61, like we do in e.g. https://github.com/i3/i3status/blob/master/src/process_runs.c

Can you send a pull request for that please?

**Comment by eplanet** [comment] 2016-03-20 10:48
Looks like a good enhancement to me, I faced the exact same issue as @f4hy. But while fiddling with the print_cpu_temperature.c file, I realized that the default path value "*/sys/class/thermal/thermal_zone%d/temp*" already does the trick by resolving %d with the provided zone input parameter (ex: *cpu_temperature 0*).

Even though the issue is still correct, one should not use info in path */sys/devices/platform/coretemp.0/* on Linux system since the default value already works. I think the documentation in the man needs to be modified to be more explicit on the subject for that purpose.

**Closed** 2016-03-21 19:19 UTC
Labels: enhancement
