### ISSUE TITLE
xmobar fmt for volume (muted) is wrong

### ISSUE THREAD

**Issue by roymath** [i3/i3status#112] opened 2016-03-08 18:01 UTC
Hi -  I need to have an explicit `</fc>` added to my config when writing out xmobar output... and the volume is muted. The following works:
```
volume master {
        format = "Vol: %volume"
        format_muted = "Vol: muted</fc>" # bugfix
        device = "default"
        mixer = "Master"
        mixer_idx = 0
}
```

Quickly scanning the code, it appears to be an issue with missing an END_COLOR step in src/print_volume.c:
```
if (muted) {
    START_COLOR("color_degraded");
    pbval = 0;
}
...

out:
    *outwalk = '\0';
    if (!pbval)
        END_COLOR;
    OUTPUT_FULL_TEXT(buffer);
}
```

**Comment by stapelberg** [comment] 2016-03-08 18:18
Can you send a pull request to fix this issue please? Most people are using i3status with i3bar, so the chances are slim that other people will fix this.

**Comment by roymath** [comment] 2016-03-08 20:29
Hello Michael - By pull request, do you mean a code fix or simply a fork
with the documentation that I already created as part of the original
ticket?

(I'm not sure how to make the code fix, since I don't see any tests in the
src tree, and don't want to break the code.)

On Tue, Mar 8, 2016 at 1:18 PM, Michael Stapelberg <notifications@github.com
> wrote:

> Can you send a pull request to fix this issue please? Most people are
> using i3status with i3bar, so the chances are slim that other people will
> fix this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/i3/i3status/issues/112#issuecomment-193898907>.
>



-- 
Roy.

**Comment by stapelberg** [comment] 2016-03-09 07:49
I meant fixing the code.

With regards to testing, you can run i3status in a terminal and see if the output looks good (use output=auto or output=terminal in your configfile to get nicely readable output).

**Comment by eplanet** [comment] 2016-09-01 21:39
What version are you running @roymath? I cannot reproduce that bug. When using the configuration you provided I get two closing marks `</fc>`, and when removing it from the configuration, I get the consistent following output:
```bash
$ ./i3status -c i3status.conf 
<fc=#FFFF00>Vol: muted</fc>
```
Support for xmobar date back from `bb52b40c8ed5b3c938f6bb157b08bcb18bb067c2`, and the closing mark `</fc>` for color has always been there since: [src/output.c#L52](https://github.com/i3/i3status/blob/master/src/output.c#L52).


P.S: By the way @stapelberg I agree that some unit testing could prove useful to i3status. What do you think?

**Comment by stapelberg** [comment] 2016-09-04 15:56
@eplanet I agree that unit testing — or any tests, really — would be a good idea. What makes testing i3status hard is the various system APIs which we’d need to mock/fake/inject somehow (that’s of course much simpler for text-based APIs such as the uevent files we read for battery status). I’m uncertain whether doing that is feasible at all, and if it is, whether we’d gain much from having the tests.

Anyway, if you’re motivated to work on testing i3status, please feel free to open another issue, or even discuss your approach over a pull request (if you don’t mind possibly making sweeping changes).

**Comment by eplanet** [comment] 2016-09-21 21:08
I propose we close this issue: the bug is not reproducible and @roymath doesn't answer.

**Comment by Airblader** [comment] 2016-09-21 21:09
I agree. If @roymath comes back with the information we can reopen.

**Closed by Airblader** 2016-09-21 21:09 UTC
