### ISSUE TITLE
Certain characters break vertical alignment

### ISSUE THREAD

**Issue by polyzen** [i3/i3status#272] opened 2018-03-26 23:09 UTC
Using certain characters (eg. 🖴 and 🌶) breaks the vertical alignment of the module they're in:
https://ptpb.pw/AvQf.png

**Comment by orestisf1993** [comment] 2018-03-26 23:46
Should be a duplicate of https://github.com/i3/i3/issues/3114

**Closed by orestisf1993** 2018-03-26 23:46 UTC
