### ISSUE TITLE
i3satus not displaying wifi

### ISSUE THREAD

**Issue by FunkyJamma** [i3/i3status#52] opened 2015-08-23 03:06 UTC
Hello Everyone,

I am having an issue where i3status shows no wlan even though im connected online

ifconfig

enp0s25: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:21:cc:bd:a6:0a  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf2500000-f2520000 

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 20  bytes 1760 (1.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 20  bytes 1760 (1.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1280
        inet 10.0.0.119  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 2601:583:703:7684:f27b:cbff:fe73:32e9  prefixlen 64  scopeid 0x0<global>
        inet6 2601:583:703:7684::ba0d  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::f27b:cbff:fe73:32e9  prefixlen 64  scopeid 0x20<link>
        ether f0:7b:cb:73:32:e9  txqueuelen 1000  (Ethernet)
        RX packets 52130  bytes 45391146 (43.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 62520
        TX packets 40658  bytes 10056064 (9.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 17

i3status.conf

order += "wireless wlp3s0"

wireless wlp3s0 {
# format_up = "W: (%quality at %essid) %ip"
format_up = "  %essid %quality "
format_down = " no wlan "
}

I have also tried _first_

**Comment by stapelberg** [comment] 2015-08-23 10:58
This might be a duplicate of #32

**Comment by cicku** [comment] 2015-09-21 04:13
OS please?

**Closed** 2015-09-24 19:48 UTC
