### ISSUE TITLE
i3status not responding to SIGUSR1 as expected

### ISSUE THREAD

**Issue by diatomine** [i3/i3status#108] opened 2016-02-03 20:50 UTC
Hello,

I do all updates of i3status manually with `killall -USR1 i3status`, every full minute with systemd, and whenever volume and network changes occur.

I use arch linux; after a full system upgrade (where i3status was updated) I noticed that i3status was only updating when I changed the volume (up, down or mute toggle).

`killall -USR1 i3status` has no effect (regardless of the executing user), while other signals terminate i3status as expected. The only way I can update it is by controlling pulseaudio: `pactl set-sink-mute 0 toggle` and `pactl set-sink-volume ...` trigger an update; `pactl list short` does not.

After downgrading from version 2.10-1 to 2.9-1, SIGUSR1 works as expected again.

**Comment by Airblader** [comment] 2016-02-03 20:51
Duplicate of #93

**Closed by Airblader** 2016-02-03 20:51 UTC
